### PR TITLE
Adding Pprof register method

### PR DESCRIPTION
**Pull request by ramiro-gamarra**
**Reason for Change**:

This PR enables pprof endpoints to be registered on the multi tenancy path.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Review by timraymond — DISMISSED** [review]
Seems reasonable to me

**Comment by rbtr** [comment]
is it feasible/should we make this dynamically registerable? if we're trying to catch a memory leak, it might be nice to be able to turn the pprof handlers on, take the heap dump, and turn them back off without restarting the process.

**Comment by ramiro-gamarra** [comment]
> is it feasible/should we make this dynamically registerable? if we're trying to catch a memory leak, it might be nice to be able to turn the pprof handlers on, take the heap dump, and turn them back off without restarting the process.

I believe we can still attach routes to the mux even after the server has started listening. Are you proposing:
1. client calls a CNS endpoint to enable pprof handlers, client calls pprof endpoint, client calls CNS endpoint to turn off pprof handlers.
2. client calls a CNS endpoint to collect pprof data, where CNS can internally use the pprof package without needing handlers.
3. something else.

I think while we decide on a more dynamic approach, it might be simpler to suggest to teams that use multi tenancy to run CNS with this turned on, since they own the ingra and there should be less risk for abuse of these endpoints.

**Comment by timraymond** [comment]
@rbtr @ramiro-gamarra Why do we need to turn the pprof handlers on and off dynamically? There's no performance penalty until you actually collect a profile.

**Comment by rbtr** [comment]
but there is _significant_ performance penalty when you do so best practice is to not leave pprof on in prod where someone could naively hit a dump endpoint and freeze the process for a minute

**Review by timraymond — APPROVED** [review]

**Pull request merged**
