### PR TITLE
ci: update to VM SKU with acclnet

### PR DESCRIPTION
**Pull request by jshr-w**
**Reason for Change**:

PR updates VM SKUs on PR pipeline to use accelerated networking.

**Issue Fixed**:

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [X] relevant PR labels added

**Notes**:

### CODE REVIEW

**Review by tamilmani1989 — APPROVED** [review]

**Comment by rbtr** [comment]
unless we are only supporting accelnet VMs, it seems like we should leave some tests on the old SKUs still?

**Comment by vipul-21** [comment]
I agree with Evan. We should have tests for non acclnet skus too. 
When you said " that is intended to be done as a separate PR." - Do you mean we will be adding all the stages/tests without acclnet or a subet of stages in the PR pipeline ?

**Comment by jpayne3506** [comment]
> @jshr-w I chose B SKUs for their cost; this change ~doubles the cost of the CI. Do we need to update _all_ of the tests to run on these SKUs?

We actually upgraded from B2 to B2ms to handle the test cases better which puts it in the same cost bracket as B2s_v2. 

Looking at the differences B2s_v2 v D2s_v3 ...

**Comment by tamilmani1989** [comment]
we can have non acclnet sku in release pipeline.. what's the default in AKS? is it acclnet enabled or disabled

**Comment by jshr-w** [comment]
AKS automatically enables acclnet if it is supported on the VM SKU

**Comment by tamilmani1989** [comment]
@vipul-21 @rbtr we can have non-acclnet in release pipeline ... no strong opinion im fine with other way as well

**Comment by jshr-w** [comment]
Closing, after discussion we have decided to change the VM SKUs on the release pipeline instead of the PR pipeline.

**Pull request closed without merging**
