### PR TITLE
fix: update default k8s ver to 1.30

### PR DESCRIPTION
**Pull request by rbtr**
**Reason for Change**:

Main branch is for release 1.6.x, which is locked to k8s 1.30. Updates the default cluster for E2Es and development to 1.30.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

### CODE REVIEW

**Review by jpayne3506 — APPROVED** [review]

**Comment by jpayne3506** [comment]
Updating to 1.30 is bringing in new tests that is only failing for windows dualstack. Currently looking into why they are failing.

**Comment by rbtr** [comment]
i'm starting to think there's a problem with the dualstack overlay test...

**Comment by jpayne3506** [comment]
So, this is exclusively impacting k8s 1.30 clusters. Not the testing that is being brought in with k8sE2E suite. 

> Warning  FailedCreatePodSandBox  2m7s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: hcs::CreateComputeSystem 41e358524cf5b069ac3c271cba38948df30276e9fdb280a1ee6b7b08684faad0: The parameter is incorrect.: unknown

Will see if there are any open issues tracking this on:
- https://github.com/microsoft/hcsshim
- https://github.com/kubernetes/kubernetes/

**Comment by jpayne3506** [comment]
Talked to @paulyufan, this could also be containerd issue.

**Comment by rbtr** [comment]
@jpayne3506 what do I need to do to get this merged?

**Pull request merged**
