### PR TITLE
[hotfix] Fix latency in transparent mode

### PR DESCRIPTION
**Pull request by tamilmani1989**
**Reason for Change**:

1. updated routes
2. added static arp entry in container namespace for virtual gw ip

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Comment by tamilmani1989** [comment]
azp /run

**Comment by tamilmani1989** [comment]
run /azp

**Review by chandanAggarwal — APPROVED** [review]
:shipit:

**Comment by matmerr** [comment]
Related https://github.com/Azure/azure-container-networking/issues/751

**Pull request merged**
