### PR TITLE
ci: Remove winio from replace( )

### PR DESCRIPTION
**Pull request by jpayne3506**
**Reason for Change**:

hcsshim@v0.12.5 requires a winio version that has `winio.NewOpenFile`. So we need to update the winio version. Before we update hcsshim we should check that this winio update does not cause any regressions. 

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [x] relevant PR labels added

**Notes**:
Loss of context for the original reasoning for replace( ) in #961 may introduce some bugs.

### CODE REVIEW

**Review by huntergregory — CHANGES_REQUESTED** [review]
I don't think NPM tests will get triggered for this PR but if we could comment here when offline tests pass for this branch, then I could sign off for NPM

**Comment by jpayne3506** [comment]
Even if the PR does not trigger the PR, we can still pair it by running the pipeline with the branch name.

**Comment by huntergregory** [comment]
> /azp run NPM Conformance Tests

whoops wrong PR

**Review by paulyufan2 — APPROVED** [review]

**Review by huntergregory — APPROVED** [review]
Thanks for verifying with Windows NPM conformance

**Pull request merged**
