### PR TITLE
Make IPVS work with CNI to ensure Service IP reachability from inside Kubernetes Pods

### LINKED ISSUE #447: IPVS doesn't work with Azure CNI
**Is this a request for help?**:
Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

---

**Which release version?**:
Latest (1.0.29)

---

**Which component (CNI/IPAM/CNM/CNS)**:
CNI

---

**Which Operating System (Linux/Windows)**:
Linux

---

**For Linux: Include Distro and kernel version using "uname -a"**
`Linux k8s-agentpool1-cen1-vmss000001 5.0.0-1023-azure #24~18.04.1-Ubuntu SMP Wed Oct 2 20:23:29 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

---

**Which Orchestrator and version (e.g. Kubernetes, Docker)**
Kubernetes 1.16.2

---

**What happened**:
When setting up a cluster with IPVS as the kubeproxy mode, on an Azure CNI enabled network, cluster IPs are not reachable via pods.

Environment details:
* Azure VNet: 10.73.0.0/16
* Service network: 172.21.0.0/16
* DNS Service IP: 172.21.255.1
* Deployment via aks-engine

When setting up a new cluster, I found that CoreDNS pods are not able to reach the cluster IP `172.21.0.1`, and throw up the following logs
```
$ kubectl -n kube-system logs coredns-56bc7dfcc6-wgb6r
E1121 01:47:48.755559       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://172.21.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 172.21.0.1:443: i/o timeout
E1121 01:47:48.755559       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://172.21.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 172.21.0.1:443: i/o timeout
E1121 01:47:48.755559       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://172.21.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 172.21.0.1:443: i/o timeout
E1121 01:47:48.755559       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://172.21.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 172.21.0.1:443: i/o timeout
E1121 01:48:19.754336       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://172.21.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 172.21.0.1:443: i/o timeout
```

Please note that the IP `172.21.0.1` is a valid cluster IP in the cluster
```
$ kubectl get svc -o wide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE     SELECTOR
kubernetes   ClusterIP   172.21.0.1   <none>        443/TCP   5d15h   <none>
```
and is reachable via the node on which the CoreDNS pod is running
```
me@k8s-agentpool1-cen1-vmss000001:~$ curl --insecure 'https://172.21.0.1:443/api/v1/services' # Run on the Node
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

As is to be expected, IPVS was correctly set up on the node (172.21.0.1:443 is pointing to API server LB IP)
```
me@k8s-agentpool1-cen1-vmss000001:~$ sudo ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  127.0.0.1:30271 rr
TCP  172.17.0.1:30271 rr
TCP  172.21.0.1:443 rr
  -> 10.73.127.234:443            Masq    1      0          0         
TCP  172.21.23.199:443 rr
TCP  172.21.166.66:443 rr
  -> 10.73.0.121:443              Masq    1      0          0         
TCP  172.21.240.234:44134 rr
  -> 10.73.0.222:44134            Masq    1      0          0         
TCP  172.21.255.1:53 rr
  -> 10.73.0.139:53               Masq    1      0          0         
TCP  172.21.255.1:9153 rr
  -> 10.73.0.139:9153             Masq    1      0          0         
TCP  10.73.0.101:30271 rr
UDP  172.21.255.1:53 rr
  -> 10.73.0.139:53               Masq    1      0          0  
```

To test, a tmp shell pod was created to fire a curl request, and as can be seen, it times out
```
$ kubectl run tmp-shell --image curlimages/curl --overrides='{"apiVersion": "v1","spec": {"nodeSelector": {"kubernetes.io/hostname": "k8s-agentpool1-cen1-vmss000001"}}}' --restart=Never --tty=true --attach=true --stdin=true --rm=true --generator=run-pod/v1 sh
If you don't see a command prompt, try pressing enter.
/ $ curl --insecure -m 10 'https://172.21.0.1:443/api/v1/services' # Run inside POD
curl: (28) Connection timed out after 10001 milliseconds
/ $ ip route show
default via 10.73.0.1 dev eth0 
10.73.0.0/17 dev eth0 scope link  src 10.73.0.108 
/ $ arp -n
? (10.73.0.1) at 12:34:56:78:9a:bc [ether]  on eth0
```

While the above curl request was being made, a tcpdump was being run on the node, showing no response packets whatsoever
```
me@k8s-agentpool1-cen1-vmss000001:~$ sudo tcpdump -nei azure0 host 172.21.0.1
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on azure0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:40:47.258612 aa:dc:92:37:36:98 > 12:34:56:78:9a:bc, ethertype IPv4 (0x0800), length 74: 10.73.0.108.47806 > 172.21.0.1.443: Flags [S], seq 2710729044, win 64240, options [mss 1460,sackOK,TS val 3312929477 ecr 0,nop,wscale 7], length 0
14:40:47.270447 ea:41:81:ec:9e:fd > 12:34:56:78:9a:bc, ethertype IPv4 (0x0800), length 74: 10.73.0.121.58652 > 172.21.0.1.443: Flags [S], seq 2890231579, win 64240, options [mss 1460,sackOK,TS val 2053885798 ecr 0,nop,wscale 7], length 0
14:40:48.262517 aa:dc:92:37:36:98 > 12:34:56:78:9a:bc, ethertype IPv4 (0x0800), length 74: 10.73.0.108.47806 > 172.21.0.1.443: Flags [S], seq 2710729044, win 64240, options [mss 1460,sackOK,TS val 3312930481 ecr 0,nop,wscale 7], length 0
14:40:50.278484 aa:dc:92:37:36:98 > 12:34:56:78:9a:bc, ethertype IPv4 (0x0800), length 74: 10.73.0.108.47806 > 172.21.0.1.443: Flags [S], seq 2710729044, win 64240, options [mss 1460,sackOK,TS val 3312932497 ecr 0,nop,wscale 7], length 0
```

As can be clearly seen above, because of CNI, the pod is sending packets destined for `172.21.0.1` (an IPVS service), wrapped in the mac address of the default gateway `10.73.0.1`. There's nothing in the current ebtables of the node to prevent this packet from being sent on the VNet, instead of being processed by the host node.
```
me@k8s-agentpool1-cen1-vmss000001:~$ sudo ebtables -t nat -Ln
Bridge table: nat

Bridge chain: PREROUTING, entries: 11, policy: ACCEPT
-p ARP -i eth0 --arp-op Reply -j dnat --to-dst ff:ff:ff:ff:ff:ff --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.73.0.121 -j arpreply --arpreply-mac ea:41:81:ec:9e:fd
-p IPv4 -i eth0 --ip-dst 10.73.0.121 -j dnat --to-dst ea:41:81:ec:9e:fd --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.73.0.139 -j arpreply --arpreply-mac 8a:e1:e2:22:fe:91
-p IPv4 -i eth0 --ip-dst 10.73.0.139 -j dnat --to-dst 8a:e1:e2:22:fe:91 --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.73.0.114 -j arpreply --arpreply-mac da:67:73:ab:32:5d
-p IPv4 -i eth0 --ip-dst 10.73.0.114 -j dnat --to-dst da:67:73:ab:32:5d --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.73.0.112 -j arpreply --arpreply-mac 42:d4:84:19:ad:b
-p IPv4 -i eth0 --ip-dst 10.73.0.112 -j dnat --to-dst 42:d4:84:19:ad:b --dnat-target ACCEPT
-p ARP --arp-op Request --arp-ip-dst 10.73.0.108 -j arpreply --arpreply-mac 92:b8:e2:17:e8:ad
-p IPv4 -i eth0 --ip-dst 10.73.0.108 -j dnat --to-dst 92:b8:e2:17:e8:ad --dnat-target ACCEPT

Bridge chain: OUTPUT, entries: 0, policy: ACCEPT

Bridge chain: POSTROUTING, entries: 1, policy: ACCEPT
-s Unicast -o eth0 -j snat --to-src 0:d:3a:f0:32:b0 --snat-arp --snat-target ACCEPT
me@k8s-agentpool1-cen1-vmss000001:~$ sudo ebtables -Ln
Bridge table: filter

Bridge chain: INPUT, entries: 0, policy: ACCEPT

Bridge chain: FORWARD, entries: 0, policy: ACCEPT

Bridge chain: OUTPUT, entries: 0, policy: ACCEPT
me@k8s-agentpool1-cen1-vmss000001:~$ sudo ebtables -t broute -Ln
Bridge table: broute

Bridge chain: BROUTING, entries: 0, policy: ACCEPT
```
---

**What you expected to happen**:
Service IPs need to be reachable from the Pods, when running a cluster with IPVS + CNI enabled on Azure.

---

**How to reproduce it** (as minimally and precisely as possible):
1. Set up an IPVS enabled cluster with CNI on Azure. I set it up using aks-engine, but I suspect the issue with show up with any other method as well.
1. Validate on any node that service IPs are configured as IPVS: `ipvsadm -Ln`
1. Validate that these service IPs are reachable from the nodes (sample command mentioned above)
1. Spawn a temp shell pod (sample command mentioned above), and try reaching any of the cluster IPs from the pod - they time out.

### PR DESCRIPTION
**Pull request by amodm**
**What this PR does / why we need it**:
This PR makes packets originating from inside the pod to go via the host stack by setting up / tearing down ebtables broute entries when a container comes up / goes down. Without this, or some other mechanism to force packets to be processed by the host stack, IPVS will not work.

**Which issue this PR fixes**:
Fixes #447 

**Special notes for your reviewer**:
This has been tested to work with both IPVS mode, and the regular iptables mode.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by amodm** [comment]
@tamilmani1989 I could be wrong here but a quick glance at the code seems to indicate that it'll require modifying a bunch of other common data structures like `network`, `NetworkInfo` etc, as `cni.NetworkConfig` isn't directly reachable from `network/bridge_endpointclient_linux.go`, which I'm presuming will have repercussions on other usages of those data structures in the rest of the code.

Would it be preferable to do this change? I'm asking because the nature of the change in the original PR is compatible with IPTables completely, as it just forces the packets (destined for cluster ips) to go via the host stack, which happens in the iptables network mode anyways.

**Comment by amodm** [comment]
@tamilmani1989 I've put this behind the flag `enableIpvs`, though I'm not sure if this was the best way to do it. I've put in a note in docs/cni.md as well for the flag.

**Comment by amodm** [comment]
@tamilmani1989 is there anything else that's needed here?

**Comment by amodm** [comment]
@tamilmani1989 is this pending on anything?

**Comment by tamilmani1989** [comment]
@amodm sorry for delayed response. We cannot check this in unless we update the network monitor code also. Network monitor runs as a daemonset in all aks clusters and it mointors l2 rules based on cni state. So this new ebtable rule will get removed by the current network monitor. Have to update network monitor to be consistent with this change

**Comment by amodm** [comment]
@tamilmani1989 can you elaborate on this? We've been running this under a (well used) test cluster for the past 2 weeks, and it has remained stable. The only change that cluster doesn't have is the conditional change (`enableIpvs` flag) you requested later.

**Comment by tamilmani1989** [comment]
@amodm my bad. networkmonitor monitors only nat table and this one is broute. So this shouldn't be a problem. Instead of enableIPVS , can we have it as disableIPVS. So there is no need to specify this flag explicitly in conflist. It will be enabled by default. The reason I asked you add this is because i'm not sure if it will cause any regression for existing scenarios.  
Once i'm done with current work, I will review this. Thanks again for this PR. Really appreciate it.

**Comment by amodm** [comment]
Done.

**Comment by tamilmani1989** [comment]
@chandanAggarwal  @aanandr

**Comment by amodm** [comment]
Any update on this?

**Comment by tamilmani1989** [comment]
@amodm  I'm working on this. I tried to create aks cluster with kubeproxy in ipvs mode..following your steps in #447 . I'm getting some issues with setup. can you help me with that. I tried to run following cmd and it returned error. Does the error mean ipvs not enabled in this cluster?

`rnmadmin@k8s-cniagtvm1-32662751-0:~$ sudo ipvsadm -Ln`
`sudo: ipvsadm: command not found
`

cluster config **change**:
"kubernetesConfig": {
            "networkPlugin": "azure",
            "networkPolicy": "azure",
            "azureCNIVersion": "",
            "azureCNIURLLinux": "",
	    **"kubeProxyMode" : "ipvs",**


share me your cluster config that would be helpful

**Comment by amodm** [comment]
`ipvsadm` is not installed by default on Azure's aks distribution, so you'll need to do `sudo apt install ipvsadm` on the node.

**Comment by tamilmani1989** [comment]
Azure CNI transparent mode is default and it supports this

**Pull request closed without merging**
