### PR TITLE
Multitenant configs for cni manager

### PR DESCRIPTION
**Pull request by pjohnst5**
**Reason for Change**:
In cni manager, allow setting cns url and enable exact match for pod name

### CODE REVIEW

**Comment by rbtr** [comment]
what's the use case?

**Comment by pjohnst5** [comment]
@rbtr for multitenancy, linux
https://msazure.visualstudio.com/One/_git/Networking-Aquarius/pullrequest/5834231

**Comment by rbtr** [comment]
i worry about allowing arbitrary URL injection at runtime, that could provide a path to privilege escalation

**Comment by pjohnst5** [comment]
What do you say @rbtr ? Given the scenario, is it okay to merge?

**Review by jaer-tsun — APPROVED** [review]
lgtm

**Comment by rbtr** [comment]
> What do you say @rbtr ? Given the scenario, is it okay to merge?

I'm not blocking 🙂

**Pull request merged**
