### PR TITLE
Remove bridgeName field from CNI windows conflist files

### PR DESCRIPTION
**Pull request by paulyufan2**
**Reason for Change**:

This PR is to cleanup windows cni config file to remove bridgeName fields

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

### CODE REVIEW

**Review by QxBytes — COMMENTED** [review]
So just confirming that "bridge" (the field) isn't used in windows, and mode will default to bridge if it is not specified? Could you also run the full pipeline with this change?

**Comment by paulyufan2** [comment]
@QxBytes  pipeline passes

**Review by QxBytes — APPROVED** [review]

**Review by QxBytes — APPROVED** [review]
On windows, a reference search for the bridgeName field of endpoint info does not reveal any usages. it seems like you're only modifying windows conflists so there shouldn't be any effect.

**Review by QxBytes — APPROVED** [review]

**Pull request merged**
