### PR TITLE
Remove hot attach for create endpoint.  Join will hot attach instead

### PR DESCRIPTION
**Pull request by plooploops**
**What this PR does / why we need it**:
Hot attach should happen in the join, not in create endpoint.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
https://github.com/Azure/azure-container-networking/issues/235
**Special notes for your reviewer**:
cnm testing

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by sharmasushant** [comment]
@plooploops  Will check... thanks for the PR.

**Comment by madhanrm** [comment]
@Plooploops  Make sure you don't break CNI. CNI needs hotadd as part of endpoint creation (Single call). Its just CNM that needs creation separately & hot add separately.

**Comment by plooploops** [comment]
Let me see if I preserve that then, thanks for the tip @madhanrm

**Comment by ashvindeodhar** [comment]
Closing this pull request as https://github.com/Azure/azure-container-networking/pull/332 is merged after discussing with Andy Gee.

**Pull request closed without merging**
