### PR TITLE
Fix for Pod Connecting to itself via ServiceIP

### LINKED ISSUE #189: POD cannot connect to itself via service ip
With the azure network plugin, a pod listening on a TCP port (say 8080), and a service fronting that pod:

The pod CAN connect back to itself via `localhost:8080`
The pod CAN connect back to itself via `<pod-ip>:8080`
The pod CAN NOT connect back to itself via `<service-ip>:8080`
Point 3 is a problem: this should be possible.

Other notes:

The node itself, as well as other pods in the system CAN connect correctly to <service-ip>:8080.
Point 3 works correctly with the kubenet network plugin, it is the azure network plugin that is at fault.

### PR DESCRIPTION
**Pull request by tamilmani1989**
…This fixes pod connecting to itself via service IP

**What this PR does / why we need it**:
Enabled hairpin on host veth interface to allow pod connecting to itself via service IP

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #189 
**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by ansant** [comment]
Any idea when the fix for this Will be implemented? Any ETA?

**Comment by tamilmani1989** [comment]
@ansant The fix is already released in v1.0.12

**Comment by digeler** [comment]
when is this version is going to be pushed to aks ?

**Comment by tamilmani1989** [comment]
I'm not sure if aks has taken this release. @jackfrancis should know it.

**Comment by jackfrancis** [comment]
@tamilmani1989 this will go into AKS next week

**Pull request merged**
