### PR TITLE
fix: replace NumCPU with NumCores

### PR DESCRIPTION
**Pull request by zhangming870**
**Reason for Change**:

replace NumCPU with NumCores, so that it can be correctly decode in dnc side.

**Issue Fixed**:

wrong request field name, should use NumCores instead of NumCPU

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Comment by rbtr** [comment]
@zhangming870 what's the context? has this just always been wrong and silently ignored, or has something changed in DNC?

**Comment by zhangming870** [comment]
> @zhangming870 what's the context? has this just always been wrong and silently ignored, or has something changed in DNC?

@rbtr We believe it always been wrong, because no one uses it yet. This is for dnc in managed mode.

**Comment by zhangming870** [comment]
good to merge

**Comment by rbtr** [comment]
@zhangming870 can you rebase? there was a fix to the CI which should improve your check results 🙂

**Comment by zhangming870** [comment]
@rbtr sure. rebased.

**Comment by rbtr** [comment]
@zhangming870 not sure what you did, but it messed up the commit history: https://github.com/Azure/azure-container-networking/pull/1358/commits
can you try and again and make sure you are _rebasing_, **not** merging master/other branches in to your branch? happy to help if you need some guidance on that.

**Review by rbtr — CHANGES_REQUESTED** [review]
commit history needs to be fixed

**Comment by zhangming870** [comment]
@rbtr rebased again and did a sync branch, I guess it pushed history to remote. thanks for letting me know how to do that. And please let me know if anything still wrong.

**Review by rbtr — APPROVED** [review]

**Review by rbtr — APPROVED** [review]

**Pull request merged**
