### PR TITLE
gRPC Server Implementation

### PR DESCRIPTION
**Pull request by Kevincxv**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

### CODE REVIEW

**Comment by timraymond** [comment]
@Kevincxv Is this different from #2745 ? If not, it's better to keep things in one PR to keep the discussion organized.

**Comment by debecerra** [comment]
@timraymond This PR is going to cover a feature that builds on top of #2745, so #2745 isn't going anywhere. This draft PR is up for visibility on the new code changes and to avoid being blocked on the review process for the prerequisite PR

**Comment by timraymond** [comment]
@debecerra Gotcha. Can we rebase it off of that branch instead of master so that way only the diffs from this work are present? That would resolve the confusion and at least make it easy to see what changed here alone.

**Comment by rbtr** [comment]
> @debecerra Gotcha. Can we rebase it off of that branch instead of master so that way only the diffs from this work are present? That would resolve the confusion and at least make it easy to see what changed here alone.

+1 rebase it on the branch in that PR instead of master, and change the target branch on this PR to that branch also. Then the diff here will only be the changes added on top of that PR.

**Pull request closed without merging**
