### PR TITLE
Lowercase ipv6 ipam to name make sure go-client finds the node

### PR DESCRIPTION
**Pull request by jsturtevant**
**Reason for Change**:

kubelet registers nodename as lowercase and Azure VMSS sets host name as Capital letters as it scales.  This makes sure we use the correct nodename by lowercasing it.

Reference issue explaining the restriction: https://github.com/kubernetes/kubernetes/issues/71140#issuecomment-439464431

**Issue Fixed**:

https://github.com/Azure/aks-engine/issues/4623

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Review by tamilmani1989 — APPROVED** [review]
lgtm

**Comment by rbtr** [comment]
thanks for reviewing @tamilmani1989

**Comment by rbtr** [comment]
thanks for the fix @jsturtevant

**Pull request merged**
