### PR TITLE
[NPM]Make order of iptables entries in UT determinisitc in case of MultipleLabelsToMultipleLabels

### PR DESCRIPTION
**Pull request by JungukCho**
**Reason for Change**:

TestAllowMultiplePodSelectors has a flake UT result due to the ordering of ipset in Specs since the order of all ipset values in Specs is not guaranteed in MultiplePodSelectors case.
Thus, in this UT, before checking the iptables entries, sorting Specs is necessary before comparing them.

You can break this UT with this script without this PR.
```shell

max=1000
idx=0
while [[ $idx -ne $max ]]
do
/usr/local/go/bin/go test -timeout 30s -v --count=1 -run ^TestAllowMultiplePodSelectors$ github.com/Azure/azure-container-networking/npm
if [[ $? -ne 0 ]]
then
	exit
fi

idx=$((idx+1))
echo $idx
done
```

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests

**Notes**:
While we have one UT to be sorted in current UTs, we need to generalize this approach in all tests to avoid undeterministic behavior in the added UTs in the future.  In addition, I feel like we need to clean up translatePolicy_test.go since it is unnecessarily too lengthy.

### CODE REVIEW

**Review by vakalapa — APPROVED** [review]
lgtm

**Comment by JungukCho** [comment]
There is another issue in this PR (sorted one can cause incorrect results as well). I will update the issue in details and codes according to the issue.

**Comment by JungukCho** [comment]
Close now. I am working on fixing this issue in another PR (refactoring  translatePolicy.go) which fundamentally fixes this issue while there are reusable commits here. I will revisit them in the other PR.

**Pull request closed without merging**
