### PR TITLE
[NPM] Remove duplicate namedports in slices to avoid unnecessary CreateSet calls in network policy controller

### PR DESCRIPTION
**Pull request by JungukCho**
**Reason for Change**:

translatePolicy function returns duplicated ipsets for namedPort if duplicated ipsets exist, which causes unnecessary call in network policy controller. While the duplicated ipset is filtered in network policy controller, it is the best to avoid the call.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Review by vakalapa — APPROVED** [review]
Lgtm, not sure how we missed this earlier. Worst case scenario we will wait a couple of ipset create calls i think. good to catch

**Review by matmerr — APPROVED** [review]
approving with the caveat that this change is a bandaid fix, the parent issue of adding duplicates requires a much larger refactor and is actively being discussed how to fix in translatepolicy

**Comment by JungukCho** [comment]
> approving with the caveat that this change is a bandaid fix, the parent issue of adding duplicates requires a much larger refactor and is actively being discussed how to fix in translatepolicy

Correct. I am working on refactoring translatepolicy.go with determinisitic UTs together in #941.

**Pull request merged**
