### PR TITLE
ci: add Cilium OS/Proc coverage to CNI Load Test pipeline

### PR DESCRIPTION
**Pull request by jpayne3506**
**Reason for Change**:

Increases coverage of cilium OS/Processor configurations on overlay clusters.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [x] relevant PR labels added

**Notes**:

### CODE REVIEW

**Review by vipul-21 — APPROVED** [review]

**Review by rbtr — APPROVED** [review]
will we be expanding the matrix on azure-vnet scenarios also?

**Comment by jpayne3506** [comment]
> will we be expanding the matrix on azure-vnet scenarios also? 

Not that I am aware of. This expansion, OS/Processor, is focused on overlay.

**Comment by rbtr** [comment]
> > will we be expanding the matrix on azure-vnet scenarios also?
> 
> Not that I am aware of. This expansion, OS/Processor, is focused on overlay.

azure-vnet supports overlay

**Comment by jpayne3506** [comment]
> > > will we be expanding the matrix on azure-vnet scenarios also?
> > 
> > 
> > Not that I am aware of. This expansion, OS/Processor, is focused on overlay.
> 
> azure-vnet supports overlay

In that case, we are only doing expansion with overlay. Thought you were referring to azure-vnet-ipam.

**Pull request merged**
