### PR TITLE
Remove Kubernetes PodInfoProvider and default to CNI initialization

### PR DESCRIPTION
**Pull request by rbtr**
**Reason for Change**:

Removes the (long deprecated) Kubernetes reconcile branch from the CNS PodInfo initialization flow. The default is now the CNI reconcile flow, with the preference to restore from CNS own managed endpoint state if that is enabled.

Slightly repackages these components to be clearer:
both are now in pkg `podprovider` instead of `cnireconciler`
CNI Pod info provider -> `podprovider/cni`
CNS endpoint state pod infor provider moved from cnireconciler -> `podprovider/cns`

Since CNI reconciliation is becoming the default, the version check can be dropped as there is no longer another option to fall back to. We simply attempt it, and verbosely error.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:
Because we don't _always_ install the CNI with CNS yet, this is not safe to release until all AKS variants are using the CNI installer init container.

### CODE REVIEW

**Comment by thatmattlong** [comment]
shall we wait to merge this until podsubnet CNI is installed with dropgz? my fear is that someone will forget that it's not ready to release until after that, and we'll break some clusters

**Comment by rbtr** [comment]
+do-no-merge +work-in-progress to be more clear that this shouldn't be merged until cni installer is default everywhere

**Comment by rbtr** [comment]
depends on #2075

**Comment by rbtr** [comment]
obsoletes/removes changes introduced in #2078

**Pull request closed without merging**
