### PR TITLE
refactor: move from io/ioutil to io and os packages

### PR DESCRIPTION
**Pull request by Juneezee**
**Reason for Change**:

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). Since this project has been upgraded to Go 1.17 in #1042, this PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Review by rbtr — APPROVED** [review]
thanks, lgtm!
/cc @ramiro-gamarra

**Comment by Juneezee** [comment]
@rbtr The Azure pipelines seems to be rate limited. I just received an email saying that the requests are being blocked.

**Comment by rbtr** [comment]
we've got some unrelated pipeline problems being fixed; will need you to rebase the PR when that is all fixed and we can move this forward

**Review by rbtr — DISMISSED** [review]

**Comment by rbtr** [comment]
hey @Juneezee we squash and merge, so unless there's conflicts you don't need to keep rebasing a minor change like this 🙂 it confuses the CI

**Review by JungukCho — APPROVED** [review]
lgtm! Thank you for contributing codes.

**Review by rbtr — APPROVED** [review]

**Comment by rbtr** [comment]
tyvm @Juneezee

**Pull request merged**
