### PR TITLE
[backport] fix/ci: Linux NPM race condition editing "except" CIDR and NPM pipeline fixes

### PR DESCRIPTION
**Pull request by huntergregory**
**Reason for Change**:
Backporting #2841 and pipeline changes for NPM Cyclonus, Conformance, and Scale Test pipelines.

**Issue Fixed**:
#2840 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [x] relevant PR labels added

**Notes**:

### CODE REVIEW

**Review by QxBytes — APPROVED** [review]
My understanding is that you're backporting multiple ci prs and a single fix which if so looks good. The linter has been failing on v1.5.x for the past few backports.

**Review by rbtr — APPROVED** [review]

**Review by vakalapa — APPROVED** [review]

**Pull request merged**
