### PR TITLE
Remove mention of unsupported "master" config parameter

### PR DESCRIPTION
**Pull request by seanknox**
**What this PR does / why we need it**: CNI currently supports 1 NIC only; this PR removes mention of the "master" config paramemter which doesn't work.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by seanknox** [comment]
fyi @saiyan86

**Comment by seanknox** [comment]
Hey @saiyan86 any issues with merging this?

**Comment by tamilmani1989** [comment]
hi @seanknox .. we support this parameter. Are you facing any issue with that parameter? This parameter can be used if there are multiple nics and which nic should be used for container networking.

**Comment by seanknox** [comment]
@tamilmani1989 according to @saiyan86 the master parameter isn't supported. Can you two doublecheck and let me know?

**Comment by tamilmani1989** [comment]
@seanknox master parameter is supported. If you find any issue with that, please file a bug.

**Comment by seanknox** [comment]
Will do, thanks!

**Pull request closed without merging**
