### PR TITLE
17871745 fix

### PR DESCRIPTION
**Pull request by paulyufan2**
PR description:

Partner team uses Upper-Case GUID (i.e, Swift_ABCASRE123A), so it's not in NMA List since the format is lower case. This PR is to Convert Upper-Case GUID to lower-case GUID to check if it can be found from ncVersionList;

This PR also includes fix to enhance cnsclient log to show users why we failed to get NCs tracking by "17871745"; for example when we create a NC with unknown orchestratorContext, it will return:
2023/04/26 16:28:19 [8608] [azure-cns] Code:UnexpectedError, {NetworkContainers:[{NetworkContainerID: IPConfiguration:{IPSubnet:{IPAddress: PrefixLength:0} DNSServers:[] GatewayIPAddress:} Routes:[] CnetAddressSpace:[] MultiTenancyInfo:{EncapType: ID:0} PrimaryInterfaceIdentifier: LocalIPConfiguration:{IPSubnet:{IPAddress: PrefixLength:0} DNSServers:[] GatewayIPAddress:} Response:{ReturnCode:UnknownContainerID Message:Failed to find networkContainerID for orchestratorContext dn112dn112} AllowHostToNCCommunication:false AllowNCToHostCommunication:false}] Response:**{ReturnCode:UnexpectedError Message:Failed to get NCs  due to Failed to find networkContainerID for orchestratorContext dn112dn112}}.**

Link to this PR: https://github.com/Azure/azure-container-networking/pull/1919

### CODE REVIEW

**Comment by rbtr** [comment]
@paulyufan2 what was the issue with the previous PR? it is just a branch in the main repo, not a fork, so any one of us should be able to modify it

**Comment by paulyufan2** [comment]
Hi @rbtr previous PR was done by this account paulyufan2 before I joined Azure org and somehow I was not able to push codes to the previous PR to make any changes.

**Comment by rbtr** [comment]
I think you should try again, if you are a member of our team/this repo, you should be able to push to that branch.

**Comment by paulyufan2** [comment]
okay let me close this PR and try previous one

**Comment by paulyufan2** [comment]
Hi @rbtr previous closed PR: https://github.com/Azure/azure-container-networking/pull/1926 had other's changes as well. Can I open a new PR from my forked repo and I can link previous PR to this new PR.

**Pull request closed without merging**
