### PR TITLE
[backport] fix: [NPM] [Linux] handle more than 15 leaked ipsets

### LINKED ISSUE #2997: [NPM] [Linux] if the kernel leaks references of 16+ ipsets, NPM remains in CrashLoop
_**NOTE: fixed in v1.5.37**_

### Symptoms

NPM Pod in CrashLoop.

Previous logs of the crashed NPM Pod look like:
```
E0904 18:22:41.928737       1 ipsetmanager_linux.go:131] failed to destroy all ipsets (prometheus metrics may be off now). destroyFailureCount 824637563208. err: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
]
E0904 18:22:41.928766       1 dataplane.go:108] Failed to reset dataplane: Operation [BootupDataplane] failed with error code [999], full cmd [], full error failed to reset ipsets dataplane: error while resetting ipsetmanager: failed to run ipset restore while destroying all for resetting IPSets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
```

### Mitigation

- Option 1: Restart the impacted Node.
- Option 2: Cordon and drain all Pods off the impacted Node.

### Cause

There is a known issue in ipset where it leaks references. Leaked references occur when there are no iptables rules referencing the ipset and the ipset is not a member of any list ipset, yet the ipset thinks it has references.

Azure NPM resets its ipset state (deleting all IPSets) when the NPM Pod boots up. During this time, NPM detects which IPSets have leaked references, and it ignores such ipsets and deletes all other NPM IPSets. However, due to a bug in NPM code, NPM will only ignore the first 11 NPM IPSets with leaked references. Due to retry logic, if there are 16 or more leaked IPSets, then NPM will enter a CrashLoop.

#### Code

https://github.com/Azure/azure-container-networking/blob/ff46b571440c1a25b2d0dcec5e2a4dcf7dcb8374/npm/pkg/dataplane/ipsets/ipsetmanager_linux.go#L231

https://github.com/Azure/azure-container-networking/blob/ff46b571440c1a25b2d0dcec5e2a4dcf7dcb8374/npm/pkg/dataplane/ipsets/ipsetmanager_linux.go#L842-L855

https://github.com/Azure/azure-container-networking/blob/ff46b571440c1a25b2d0dcec5e2a4dcf7dcb8374/npm/pkg/dataplane/ipsets/ipsetmanager_linux.go#L24

### PR DESCRIPTION
**Pull request by huntergregory**
**Reason for Change**:
Backport #2998

**Issue Fixed**:
Fixes #2997 in release/v1.5 branch

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [x] relevant PR labels added

### CODE REVIEW

**Comment by huntergregory** [comment]
Scale test flaked:
> Error from server: error dialing backend: EOF
[2024-09-11 23:12:37+00:00] WARNING: expected scale Pod real-agnhost-dep-00004-5b4b779894-7wjc9 to be able to connect to scale Pod real-agnhost-dep-00009-85c5d7c449-vmw2b
[2024-09-11 23:12:37+00:00] ERROR: initial connectivity test timed out. Last try was about 262 seconds after pinger Pods began running

**Comment by huntergregory** [comment]
Scale test passed here: https://msazure.visualstudio.com/One/_build/results?buildId=102998108&view=results

The "Rerun" option is broken for the scale test pipeline.

**Review by rayaisaiah — APPROVED** [review]

**Pull request merged**
