### PR TITLE
fix: Rename test file

### PR DESCRIPTION
**Pull request by bohuini**
**Reason for Change**:
Fixed the naming of ut file and fixed bugs in UT.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

### CODE REVIEW

**Comment by shreyashastantram** [comment]
Please ensure that these tests runs in pipeline

**Comment by bohuini** [comment]
> Please ensure that these tests runs in pipeline

@shreyashastantram  https://msazure.visualstudio.com/One/_build/results?buildId=95803932&view=results

**Review by shreyashastantram — APPROVED** [review]

**Review by paulyufan2 — APPROVED** [review]

**Pull request merged**
