### PR TITLE
fix: Add missing CNI invoker delete calls

### PR DESCRIPTION
**Pull request by matmerr**
**Reason for Change**:

All add calls and delete calls should be via the invoker interface, this fix is to change DelegateDel's to invoker.Delete, which is required in swift mode

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Review by neaggarwMS — DISMISSED** [review]

**Comment by matmerr** [comment]
> Do we need to add nil check for nwCfg?

there aren't any checks in the existing path for a nil nwCfg

**Review by neaggarwMS — APPROVED** [review]

**Pull request merged**
