### PR TITLE
chore: must* functions should panic

### PR DESCRIPTION
**Pull request by pjohnst5**
`must*` functions should panic, not return `err`

Targeting the `test/internal/kubernetes` package in this PR

### CODE REVIEW

**Review by ecigar13 — APPROVED** [review]

**Review by rbtr — DISMISSED** [review]

**Comment by pjohnst5** [comment]
These CNI Load test failures don't block, they are a different testing pipeline that John and the Cilium folks use to test CNI load tests with Cilium

Right now, I see errors about a deployment not being able to be modified because it has been altered (likely due to a duplicate run or re-run of the pipeline since I've been trying over and over), and another about quota being too low in the sub

I think we can write that off as unrelated, we actually run the same code now in the ACN PR pipeline anyways, so we know those code paths are being hit

**Review by vipul-21 — APPROVED** [review]

**Pull request merged**
