### PR TITLE
feat: include swift-overlay.conflist in the dropgz build

### PR DESCRIPTION
**Pull request by tyler-lloyd**
adds the azure-swift-overlay.conflist in the dropgz build file so Azure CNI Overlay clusters can use the dropgz to install the cni.

Signed-off-by: Tyler Lloyd <tylloyd@microsoft.com>

**Reason for Change**:

Adds the [azure-swift-overlay](https://github.com/Azure/azure-container-networking/blob/95155ca9b4079cfe9ce4e93c04de419e28a3ad3c/cni/azure-linux-swift-overlay.conflist) conflist to dropgz's build process so that it can be loaded onto a host without the conflist.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Review by rbtr — APPROVED** [review]
lgtm

**Review by rbtr — APPROVED** [review]

**Comment by timraymond** [comment]
What is this file, and what does it do? I understand what `dropgz` does, but it would be helpful for reviewers (like me) without context to have a "here is the problem, here is why this proposed change solves this problem" answered in the description of the PR.

**Comment by rbtr** [comment]
@timraymond the description already answers that, to my reading. Do you disagree? 
This being the repo for a CNI impl, I think we have to assume familiarity with CNI fundamentals like the function of the conflist in general.

**Review by rbtr — APPROVED** [review]

**Pull request merged**
