### PR TITLE
Update to cilium v1.12.8

### PR DESCRIPTION
**Pull request by camrynl**
**Reason for Change**:

Pipelines will now test with cilium v1.12.8

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Comment by rbtr** [comment]
what's the plan for larger migrations? should we parameterize this out into a(nother) test matrix so we can do [1.12.8, 1.13.x] etc?

**Review by rbtr — DISMISSED** [review]

**Comment by camrynl** [comment]
> what's the plan for larger migrations? should we parameterize this out into a(nother) test matrix so we can do [1.12.8, 1.13.x] etc?

For now, we just test the next version against our load tests and the pr pipeline. Do you mean to have a separate pipeline where we can test multiple versions at once?

**Comment by rbtr** [comment]
I imagine it would be straightforward to run this pipeline as a matrix with the version parameterized. Like how we do ARM/AMD, so that we can transition in to new versions of the dependency without a hard cutover.

**Comment by camrynl** [comment]
> I imagine it would be straightforward to run this pipeline as a matrix with the version parameterized. Like how we do ARM/AMD, so that we can transition in to new versions of the dependency without a hard cutover.

I see, I will move towards parameterized versions in future states

**Pull request merged**
