### PR TITLE
update to go1.20

### PR DESCRIPTION
**Pull request by rbtr**
Signed-off-by: Evan Baker <rbtr@users.noreply.github.com>

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

### CODE REVIEW

**Review by huntergregory — COMMENTED** [review]
NPM changes lgtm. Let's see how pipelines fare

**Comment by rbtr** [comment]
@huntergregory everything is green except for `Run Windows Cyclonus v2-windows`

**Comment by ramiro-gamarra** [comment]
As of today, go 1.20.2 is the latest stable release, should we specify the minor version here?

**Comment by rbtr** [comment]
> As of today, go 1.20.2 is the latest stable release, should we specify the minor version here?

We will get the latest available patch versions automatically by only specifying the major.minor version

**Review by ramiro-gamarra — APPROVED** [review]

**Pull request merged**
