### PR TITLE
Default to accelnet behavior in CNI for SwiftV2 windows

### PR DESCRIPTION
**Pull request by kmurudi**
**Reason for Change**:
1. Starting v1.6.5 we disabled the use of or passing "cns.NodeNetworkInterfaceAccelnetFrontendNIC" from swiftV2 middleware because it is not supported for swiftv2 Linux CNI programming.
2. For L1VH scenario i.e. the current Windows swiftV2 we decided to default any vnet device programming to be supporting VF i.e. accelerated networking whether the interface on the VM supports it or not & expect HNS to program accordingly.
3. This removes all mentions of "cns.NodeNetworkInterfaceAccelnetFrontendNIC" in CNI for windows/linux since it is now not passed from middleware k8sSwiftV2 at all.
4. CNI Linux files don't need change as accelnet was not supported earlier as well (leading to 1.)
5. CNI windows files now default to all HNS/CNI settings for VF(Accelnet) while using "cns.NodeNetworkInterfaceFrontendNIC" as passed by CNS. remove any settings done for non-VF.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

### CODE REVIEW

**Review by tamilmani1989 — APPROVED** [review]
lgtm. @paulyufan to review.

**Review by paulyufan2 — APPROVED** [review]

**Review by miguelgoms — APPROVED** [review]

**Review by QxBytes — APPROVED** [review]

**Pull request merged**
